### PR TITLE
Update landing with chain logos

### LINKED ISSUE #4: Update landing with chain logos
1) Move social icons to the top-right
2) Add Chain icons with current hover animations

fix

Icons: [wetransfer-72e221.zip](https://github.com/beefyfinance/beefy-landing/files/6390683/wetransfer-72e221.zip)

### PR DESCRIPTION
**Pull request by JordanRaphael**
Resolves #4 , The links are working, but the browser wasn't rendering the icons (used Makefile). If you can check that the icons are working, you can merge :)

### CODE REVIEW

**Comment by roman-monk** [comment]
no, it's not 😄

image

**Comment by roman-monk** [comment]
try "make" and "serve -s dist" 🙏

**Comment by JordanRaphael** [comment]
Thanks to YR2150, I added new images and rearranged the page a bit. 👍

**Review by ghost — DISMISSED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
Almost working on my end too.
The icons in the center of the screen are not visible, and the 'docs' svg is huge :(

**Comment by JordanRaphael** [comment]
> Almost working on my end too.
> The icons in the center of the screen are not visible, and the 'docs' svg is huge :(

I had these issues too, I remember that the SVGs weren't visible, changing them to PNGs did the trick. What OS are you using?

edit: I downloaded the commit again to have a fresh copy, run "make all" and "serve -s dist", and works fine.
Could you try "make clean" please?

**Comment by JordanRaphael** [comment]
Could someone else download this commit and test it as well? 

I've re-downloaded this PR and I can't reproduce the issue.

landing

**Comment by ReflectiveChimp** [comment]
Looks fine to me apart from IE11 (which is perfectly acceptable).

Note that it looks like Fantom will be added soon; so there will be another logo to add.

macOS-Big-Sur-Firefox-87:
macOS-Big-Sur-Firefox-87

macOS-Big-Sur-Opera-75:
macOS-Big-Sur-Opera-75

macOS-Big-Sur-Safari-14:
macOS-Big-Sur-Safari-14

macOS-Big-Sur-Chrome-90:
macOS-Big-Sur-Chrome-90

macOS-Big-Sur-Edge-90:
macOS-Big-Sur-Edge-90

Windows-10-Firefox-87:
Windows-10-Firefox-87

Windows-10-Opera-75:
Windows-10-Opera-75

Windows-10-Chrome-90:
Windows-10-Chrome-90

Windows-10-Edge-90:
Windows-10-Edge-90

Windows-10-IE-11:
Windows-10-IE-11

**Comment by JordanRaphael** [comment]
Added Fantom as it was suggested by @ReflectiveChimp.
YR2150 provided the icon as always 🙏 
@superbeefyboy I don't want to tag everyone, could any dev review again please ? 😃

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
responsive
The new icons break in mobile.

One temp solution could be to have 2 sets of links. one on the nav bar, and others under the chain links, and hide them in mobile.

**Comment by JordanRaphael** [comment]
> responsive
> The new icons break in mobile.
> 
> One temp solution could be to have 2 sets of links. one on the nav bar, and others under the chain links, and hide them in mobile.

Ready for review when you are available :)

**Pull request merged**
